const experiences = [
    { name: "react", color: 'blue'},
    { name: "bazel", color: 'blue'},
    { name: "vulkan", color: 'blue'},
    { name: "image-processing", color: 'blue'},
    { name: "machine-learning", color: 'blue'},
    { name: "server", color: 'blue'},
    { name: "database", color: 'blue'},
    { name: "yocto-linux", color: 'blue'},
    { name: "qt", color: 'blue'},
    { name: "wpf-gui", color: 'green'},
    { name: "visual-studio", color: 'green'},
    { name: "cmake", color: 'green'},
    { name: "directX", color: 'green'},
    { name: "networking", color: 'green'},
    { name: "scripting", color: 'green'},
    { name: "metal", color: 'red'},
    { name: "xcode", color: 'red'},
    { name: "makefile", color: 'grey'},
    { name: "cpu-graphics-pipeline", color: 'grey'},
    { name: "cpu-raytracing", color: 'grey'},
    { name: "stm32", color: 'orange'},
    { name: "system-verilog", color: 'cyan'},
    { name: "cpu-architecture", color: 'cyan'},
    { name: "llvm", color: 'cyan'},
    { name: "threejs", color: 'hotpink'},
]

export default experiences